monitoring:
  check_interval: 5
  log_name: Application
  tracked_apps:
  - chrome.exe
  - firefox.exe
  - explorer.exe
telegram:
  allowed_users: []
  bot_token: 7863303978:AAFAROJPKxDGfRMgd2rL-0eny8_CUZHWEI0
  chat_id: 7863303978
video:
  url: https://www.youtube.com/watch?v=xm3YgoEiEDc&ab_channel=10Hours
